"""empty message

Revision ID: 5287eafa4a99
Revises: 7f43f3270b92
Create Date: 2017-10-11 20:10:55.702821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5287eafa4a99'
down_revision = '7f43f3270b92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body')
    # ### end Alembic commands ###
